# This GitHub workflow deploys Bundle assets (ML asset config and more)
# defined under my_mlops_project/assets/*
# and my_mlops_project/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for my-mlops-project Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my_mlops_project

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: my-mlops-project-staging-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.211.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t stg
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t stg
